name: dhc api docker build

on:
  workflow_dispatch:
  push:
    branches:
      - latest
    paths:
      - 'src/projects/digital-health-check/discovery/dhc/src/dhcapi/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: "{{context}}/dhcapi/Dockerfile"
          context: "{{defaultContext}}/src/projects/digital-health-check/discovery/dhc/src"
          push: false
          tags: user/app:latest